name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies (Linux)
      run: |
          sudo apt-get update
          sudo apt-get install build-essential g++ cmake ninja-build libsdl2-dev
    - name: build
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Debug ..
        cmake --build .
