name: CI Windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Windows (${{ matrix.configuration }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        configuration: [Debug, Release]
        include:
          - generator: "Visual Studio 16 2019"
            os: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
          choco install -y --no-progress cmake --install-arguments="ADD_CMAKE_TO_PATH=System"
          choco install -y --no-progress visualstudio2019community
    - name: Install SDL2
      shell: powershell
      run: |
        Invoke-WebRequest -Uri "https://www.libsdl.org/release/SDL2-devel-2.26.5-VC.zip" -OutFile "SDL2-devel-2.26.5-VC.zip"
        Expand-Archive -Path SDL2-devel-2.26.5-VC.zip
        echo "SDL2_DIR=$(pwd)\SDL2-devel-2.26.5-VC\SDL2-2.26.5\" >>${env:GITHUB_ENV}
    - name: Build
      run: |
        mkdir build
        cd build
        cmake -G ${{ matrix.generator }} -DCMAKE_BUILD_TYPE=${{ matrix.configuration }} ..
        cmake --build .
